# Generated by Django 5.0.3 on 2024-03-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('time', models.TimeField(verbose_name='Время начала выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('sign_nice_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('interval', models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_week', 'Один раз в неделю'), ('once_a_month', 'Один раз в месяц'), ('once_a_year', 'Один раз в год')], default='once_a_day', max_length=100, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=200, null=True, verbose_name='Награда')),
                ('duration_time', models.TimeField(verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('associated_nice_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nice_habit', to='habits.nicehabit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
