# Generated by Django 5.0.3 on 2024-03-25 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'Один раз в день'), ('once_a_two_day', 'Один раз в два дня'), ('once_a_three_day', 'Один раз в три дня'), ('once_a_four_day', 'Один раз в четыре дня'), ('once_a_five_day', 'Один раз в пять дней'), ('once_a_six_day', 'Один раз в шесть дней'), ('once_a_seven_day', 'Один раз в семь дней')], default='once_a_day', max_length=100, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='nicehabit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
